In [89]:
import datetime   
import tabulate

In [90]:
#import Table 2 data


MemberID = ['100001','100002','100003','100004','100004','100005','100006','100007','100007']
AdmissionID = ['1256', '3965', '5869', '9396', '0684', '3859', '1849', '3498', '1350']
Sex = ['M', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'M']
AdmissionDate = [datetime.date(2018,1,1), datetime.date(2018,2,28), datetime.date(2018,3,14), datetime.date(2018,3,20), datetime.date(2018,6,3), datetime.date(2018,10,29), datetime.date(2018,7,12), datetime.date(2018,1,2), datetime.date(2018,8,4)]
DischargeDate = [datetime.date(2018,1,4), datetime.date(2018,3,15), datetime.date(2018,4,15), datetime.date(2018,4,1), datetime.date(2018,6,30), datetime.date(2018,11,15), datetime.date(2018,7,20), datetime.date(2018,1,15), datetime.date(2018,8,16)]
DRG = ['061', '291', '349', '292', '293', '291', '543', '470', '471']


# a. Describe the steps you would take to review and clean this dataset for any data errors or inconsistencies.

Since February 2018 has only 28 dates, AdmissionDate for MemberID '100002' should change to 2/28/2018

Make a string type for MemberID, AdmissionID, Sex, and DRG.
Make a datetime type for AdmissionDate and DischargeDate.




# b.	Write code to output a new table from Table 2 that only includes admissions that end before June 30, 2018. How many admissions in the Table 2 excerpt would be included in the new table?


In [91]:
table =[["MemberID","AdmissionID","Sex","AdmissionDate","DischargeDate","DRG"]]
for i in range(0,len(MemberID)):
  if AdmissionDate[i] <datetime.date(2018,6,30):
    row = [MemberID[i],AdmissionID[i],Sex[i],AdmissionDate[i].strftime("%m/%d/%Y"),DischargeDate[i].strftime("%m/%d/%Y"),DRG[i]]
    table.append(row)


In [92]:
table

[['MemberID', 'AdmissionID', 'Sex', 'AdmissionDate', 'DischargeDate', 'DRG'],
 ['100001', '1256', 'M', '01/01/2018', '01/04/2018', '061'],
 ['100002', '3965', 'F', '02/28/2018', '03/15/2018', '291'],
 ['100003', '5869', 'F', '03/14/2018', '04/15/2018', '349'],
 ['100004', '9396', 'M', '03/20/2018', '04/01/2018', '292'],
 ['100004', '0684', 'F', '06/03/2018', '06/30/2018', '293'],
 ['100007', '3498', 'M', '01/02/2018', '01/15/2018', '470']]

# c. Write code to output the number of unique members in this dataset.


In [93]:
EachMember = list(set(MemberID))
UniqueMembers=[]
MemberCount=[]
for i in EachMember:
  MemberCount.append(MemberID.count(i))


In [94]:
for i in range(0,len(EachMember)):
  if MemberCount[i] ==1:
    UniqueMembers.append(EachMember[i])


In [95]:
UniqueMembers, len(UniqueMembers)

(['100001', '100003', '100006', '100002', '100005'], 5)

There are 5 unique members

# d. You are asked to identify all admissions for heart failure in this dataset. Heart failure admissions are identified as those with DRGs 291, 292, or 293. Write code to output a table that only contains the heart failure admissions. How many admissions in the Table 2 excerpt would be included in the new table? How many unique members in the Table 2 excerpt would be included in the new table?

In [96]:
HFA = ['291','292','293']
HFAList =[["MemberID","AdmissionID","Sex","AdmissionDate","DischargeDate","DRG"]]
for i in range(0,len(MemberID)):
  for x in HFA:
    if x ==DRG[i]:
      row = [MemberID[i],AdmissionID[i],Sex[i],AdmissionDate[i].strftime("%m/%d/%Y"),DischargeDate[i].strftime("%m/%d/%Y"),DRG[i]]
      HFAList.append(row)


In [97]:
HFAList

[['MemberID', 'AdmissionID', 'Sex', 'AdmissionDate', 'DischargeDate', 'DRG'],
 ['100002', '3965', 'F', '02/28/2018', '03/15/2018', '291'],
 ['100004', '9396', 'M', '03/20/2018', '04/01/2018', '292'],
 ['100004', '0684', 'F', '06/03/2018', '06/30/2018', '293'],
 ['100005', '3859', 'F', '10/29/2018', '11/15/2018', '291']]

There are four admissions, MemberID '100002' and '100005' are unique.